version: "3.8"

services:
  club-portal:
    build: .
    image: club-portal
    container_name: club-portal
    ports:
      - 8080:8080
    networks:
      - redis-network
      - mariadb-network
    secrets:
      - config
    depends_on:
      - redis
      - mariadb
    restart: on-failure

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - redis-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./cfg/mariadb/conf:/etc/mysql/conf.d
      - ./cfg/mariadb/sql:/docker-entrypoint-initdb.d
      - ./images:/root/images
      - ./thumbnails:/root/thumbnails
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_pass
      MYSQL_DATABASE: club_portal
    networks:
      - mariadb-network
    secrets:
      - db_pass

networks:
  redis-network:
    driver: bridge
  mariadb-network:
    driver: bridge

secrets:
  config:
    file: ./cfg/config.toml
  db_pass:
    file: ./cfg/db_pass
