version: "3.8"

services:
  club-portal:
    build: .
    image: club-portal
    container_name: club-portal
    ports:
      - "8080:8080"
    volumes:
      - ./images:/root/images
      - ./thumbnails:/root/thumbnails
    networks:
      - redis-network
      - mariadb-network
    secrets:
      - config
    depends_on:
      redis:
        condition: service_started
      mariadb:
        condition: service_healthy

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - redis-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - ./cfg/mariadb/conf:/etc/mysql/conf.d
      - ./cfg/mariadb/sql:/docker-entrypoint-initdb.d
      - ./cfg/mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_pass
      MYSQL_DATABASE: club_portal
    networks:
      - mariadb-network
    secrets:
      - db_pass
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  redis-network:
    driver: bridge
  mariadb-network:
    driver: bridge

secrets:
  config:
    file: ./cfg/config.toml
  db_pass:
    file: ./cfg/db_pass
