// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package router

import (
	"github.com/lc-tut/club-portal/router/data"
	"go.uber.org/zap"
)

// Injectors from router_wire.go:

func newServer(logger *zap.Logger) (*Server, error) {
	store, err := newRedisServer()
	if err != nil {
		return nil, err
	}
	engine := newGinEngine(logger, store)
	sessionCookieOption := data.NewSessionCookieOption()
	csrfCookieOption := data.NewCSRFCookieOption()
	config := data.NewOAuth2Config()
	whitelistInfo := data.NewWhitelist()
	dataConfig := &data.Config{
		SessionCookieOptions: sessionCookieOption,
		CSRFCookieOptions:    csrfCookieOption,
		GoogleOAuthConfig:    config,
		WhitelistUsers:       whitelistInfo,
	}
	server := registerRouters(engine, dataConfig, logger)
	return server, nil
}
