name: Docker

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - examples/*
      - .gitignore
      - LICENSE
      - README.md

  release:
    types:
      - published

jobs:
  push:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add image tag (master)
        if: github.ref == 'refs/heads/master'
        run: |
          COMMITID=$(git rev-parse --short ${{ github.sha }})
          echo "DOCKER_TAG=master-${COMMITID}" >> $GITHUB_ENV

      - name: Add image tag (dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          COMMITID=$(git rev-parse --short ${{ github.sha }})
          echo "DOCKER_TAG=dev-${COMMITID}" >> $GITHUB_ENV

      - name: Add image tag (release)
        if: github.event_name == 'release'
        run: echo "DOCKER_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/lc-tut/club-portal:${{ env.DOCKER_TAG }}
