name: Docker

on:
  push:
    branches:
      - master
    paths-ignore:
      - examples/*
      - .gitignore
      - LICENSE

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME_KASH }}
          password: ${{ secrets.PAT_KASH }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lc-tut/club-portal:master
