name: redoc

on:
  push:
    branches:
      - dev
    paths:
      - openapi.yaml
  workflow_dispatch:

jobs:
  redoc:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npx redoc-cli
        run: npx redoc-cli bundle openapi.yaml -o redoc/index.html
      - name: deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./redoc
          publish_branch: redoc
          cname: club-portal-api.linux.it.teu.ac.jp
